version: '1.0.{build}'
image: Visual Studio 2019
init:
  - cmd: git config --global core.autocrlf true
before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    - cmd: dotnet restore CanonicalEmail.sln --verbosity m
build_script:
    - cmd: dotnet pack -c Release --output artifacts src/CanonicalEmails.csproj
test_script:
  - cmd: dotnet test tests/CanonicalEmails.Tests.csproj
artifacts:
 - path: 'artifacts\**\*.nupkg'
   type: NuGetPackage
skip_commits:
  files:
    - '**/*.md'
